---
# tasks file for dotfiles-role

- import_tasks: cloned_dotfiles.yml
  tags: ['never', 'install', 'clone-dotfiles', 'deploy']

- import_tasks: cloned_git_repo.yml
  tags: ['never', 'install', 'clone-git-repo', 'deploy']

# run with --become
- import_tasks: installed_module.yml
  tags: ['never', 'install', 'install-module', 'deploy']

- import_tasks: installed_package.yml
  tags: ['never', 'install', 'install-package', 'brew-install', 'deploy']

- import_tasks: installed_oh_my_zsh.yml
  tags: ['never', 'install', 'install-oh-my-zsh', 'deploy']

- import_tasks: installed_package.yml
  tags: ['never', 'install', 'install-package', 'deploy']

- import_tasks: installed_private_git_repo.yml
  tags: ['never', 'install', 'install-private-git-repo', 'deploy']

- import_tasks: installed_stow.yml
  tags: ['never', 'install', 'install-stow', 'deploy']

- import_tasks: stowed.yml
  tags: ['never', 'stow', 'deploy']

- import_tasks: brew_started_service.yml
  tags: ['never', 'brew-start', 'deploy']

- shell: /bin/echo "You need to execure playbook with specified tags"
